# Package Overview
package_name: regression_model

# Data Files
# training_data_file: train.csv
# test_data_file: test.csv

url: https://docs.google.com/spreadsheets/d/1l4Ea9PXEXv_GwcIWTORX_oK6TgZds7yTrek-fGLbJq8/gviz/tq?tqx=out:csv&sheet=Housing_in_Eziobodo

# Variables
# The variable we are attempting to predict (Rent)
target: Rent

pipeline_name: regression_model
pipeline_save_file: regression_model_output_v

features:
  - Storeys
  - Cheaperflrs
  - LgCond
  - Age
  - GenHouse
  - Parking
  - Distance
  - Location
  - RdCond
  - SecurityLvl
  - RmSize
  - RmCond
  - Wdrobe
  - Finishing
  - Balcony
  - KitchenSize
  - BathrmSize
  - BalcnySize
  - RefDisposal
  - LodgeGen
  - SecPost
  - Solar
  - RunWater
  - Cleaners
  - Electricity
  - ElecLodgeGen

# set train/test split
test_size: 0.3

# to set the random seed
random_state: 0

alpha: 0.044

# categorical variables with NA in train set
numerical_vars_with_na:
  - KitchenSize
  - BathrmSize 
  - BalcnySize

# variables to map
some_vars:
  - Cheaperflrs
  - GenHouse
  - Parking
  - Wdrobe
  - Balcony

more_vars:
  - RefDisposal
  - LodgeGen
  - SecPost
  - Solar
  - RunWater
  - Cleaners
  - Electricity
  - ElecLodgeGen

location_vars:
  - Location

finishing_vars:
  - Finishing

# variable mappings
some_mappings:
  No: 1
  I don't know: 2
  Yes: 3

more_mappings:
  false: 1
  true: 2


location_mappings:
  Near Eziobodo Gate: 1
  Near Sekani: 2
  Around John Paul's Kitchen: 3 
  Dombolo: 4
  Eziobodo Elu: 5

finishing_mappings:
  Tiles: 1
  Cement: 2